import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

export const runtime = "edge";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "つくねサーバー",
  description: "つくねさーばー　Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#121212] text-gray-200 antialiased">
        {/* --- 固定ヘッダー --- */}
        <header className="sticky top-0 z-50 w-full border-b bg-white/80 backdrop-blur-md">
          <div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4">
            <Link href="/" className="flex items-corner">
              <Image
                src="/img/つくねさーばー.webp"
                alt="つくねさーばーロゴ"
                width={250}
                height={88}
                className="object-countain"
              />
            </Link>
            {/* 右側のナビゲーションメニュー */}
            <nav className="flex gap-6 text-sm font-medium">
              <Link href="/" className="hover:text-blue-600 transition-colors">
                トップ
              </Link>
              <Link
                href="/blog"
                className="hover:text-blue-600 transition-colors"
              >
                ブログ
              </Link>
              <Link
                href="/about"
                className="hover:text-blue-600 transition-colors"
              >
                About
              </Link>
              <Link
                href="/server"
                className="hover:text-blue-600 transition-colors"
              >
                サーバー
              </Link>
              <Link
                href="/contact"
                className="hover:text-blue-600 transition-colors"
              >
                Contact
              </Link>
            </nav>
          </div>
        </header>

        <main className="mx-auto max-w-5xl px-4 py-8">{children}</main>

        <footer className="border-t bg-white py-10 mt-20">
          <div className="mx-auto max-w-5xl px-4 text-center text-gray-500">
            <p>© 2026 Tsukune Server</p>
            <div className="mt-4 flex justify-center gap-4">
              <a href="https://github.com/..." className="hover:underline">
                GitHub
              </a>
              <a href="https://youtube.com/" className="hover:underline">
                YouTube
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
